### PR TITLE
Added Basic Chemistry class, Metallurgy and Refractory Metal Processing

### LINKED ISSUE #9: Metallurgy Overhaul
WIP

### PR DESCRIPTION
**Pull request by BorisMulder**
Added:
* Tons of new materials, items, recipes, and processing chains
* New multiblock machines, including but not limited to the Blast Furnace, Basic Oxygen Furnace, Shaft Furnace and Electric Arc Furnace

Fixes #9

### CODE REVIEW

**Comment by bioastroiner** [comment]
The new stuff look pretty nice especialy the processing chain and the multiblocks, this PR is looking great. 

There is some small issues i noticed like there is one recipe in steel making that dosen't take air as input and such, i think there might be other small bugs but nothing major i noticed it looks very decent.

**Comment by BorisMulder** [comment]
Thanks for your checks, what recipe do you think is not right?

**Comment by bioastroiner** [comment]
image
this recipe dosent look intended

**Comment by BorisMulder** [comment]
> is there something else you wanna do with this PR?
No, I just wanted to keep it open in case someone would comment and will merge when I have fixed the bugs that were found
It does probably contain more bugs but its quite large, so I hope those will come up during alpha testing.
This whole feature kinda grew beyond what I expected so it's unusually large. In general I prefer smaller PRs and features.

**Comment by BorisMulder** [comment]
>  this recipe dosent look intended

I found that this was an issue of GT6, not of my mod.
Greg has pushed a fix to his repo already.
I will wait with bumping the GT6 version though until either a release of gt6x is made or something blocks my progression. The air missing out on that recipe is purely a cosmetic issue in the fake recipe, and the crucible itself still requires air to make steel.

**Pull request merged**
